spring.datasource.url=jdbc:postgresql://localhost:5432/contact_agenda
spring.datasource.username=postgres
spring.datasource.password=vagner123465

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

